nameOverride: product-service
image:
  repository: "minh4862/product-service"
  tag: "sha-682097a"
service:
  port: 3002
env:
  NODE_ENV: staging
  RABBITMQ_EXCHANGE: domain.events
  JWT_AUDIENCE: ecommerce-api
  JWT_ISSUER: auth-service
  LOG_LEVEL: info
envSecretRefs:
  - product-service-secrets # DATABASE_URL, RABBITMQ_URL, JWT_PUBLIC_KEY
networkPolicy:
  enabled: true
  allowExternal: false
