apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/minhnv0810/backend-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/minhnv0810/backend-gitops.git
      targetRevision: main
      path: charts/service
      helm:
        valueFiles:
          - $values/charts/auth-service/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
